FROM despotjakimovski/openjdk-debian-plus-few-libs

RUN apt-get install libssl1.0 libcrypto++6

# was solving some mistake before. Trying without it:
#RUN /sbin/ldconfig -v

#RUN yum install numactl-libs.i686 numactl-libs.x86_64
#RUN apt-get install numactl-libs.i686 numactl-libs.x86_64

ADD target/migration-tool-1.0-SNAPSHOT.jar app.jar
EXPOSE 1111
EXPOSE 2222
# ENTRYPOINT ["java","-jar","/app.jar","country"]

#CMD ["mysqld"]
